export const READ_DATA_LOADING = "READ_DATA_LOADING";
export const READ_DATA_SUCCESS = "READ_DATA_SUCCESS";
export const READ_DATA_ERROR = "READ_DATA_ERROR";
export const UPDATE_COLUMNS_DATA = "UPDATE_COLUMNS_DATA";
export const UPDATE_FILTER_DATA = "UPDATE_FILTER_DATA";
export const FILTER_DATA = "FILTER_DATA";
export const RESET_FILTER_DATA = "RESET_FILTER_DATA";
export const UPDATE_QUERY_PAGE_DATA = "UPDATE_QUERY_PAGE_DATA";
export const UPDATE_QUERY_MAXROWINPAGE_DATA = "UPDATE_QUERY_MAXROWINPAGE_DATA";
export const RESET_QUERY_DATA = "RESET_QUERY_DATA";
export const UPDATE_QUERY_ORDER_DATA = "UPDATE_QUERY_ORDER_DATA";
export const RESET_QUERY_ORDER_DATA = "RESET_QUERY_ORDER_DATA";
export const UPDATE_QUERY_SEARCH_VALUE_DATA = "UPDATE_QUERY_SEARCH_VALUE_DATA";
export const RESET_DATA = "RESET_DATA";
/**
 *
 */
export const CREATE_DATA_LOADING = "CREATE_DATA_LOADING";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_ERROR = "CREATE_DATA_ERROR";
export const UPDATE_DATA_LOADING = "UPDATE_DATA_LOADING";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_ERROR = "UPDATE_DATA_ERROR";
export const DELETE_DATA_LOADING = "DELETE_DATA_LOADING";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR = "DELETE_DATA_ERROR";
export const RESET_DATA_CUD_STATUS = "RESET_DATA_CUD_STATUS";
