export const CREATE_FORM = "CREATE_FORM";
export const EDIT_FORM = "EDIT_FORM";
export const ADD_FORM = "ADD_FORM";
export const CANCEL_CORE_FORM_EDIT_ADD = "CANCEL_CORE_FORM_EDIT_ADD";

export const FORM_DATA_SAVE = "FORM_DATA_SAVE";
export const FORM_DATA_READ_LOADING = "FORM_DATA_READ_LOADING";
export const FORM_SUBMIT_LOADING = "FORM_SUBMIT_LOADING";
export const FORM_SUBMIT_SUCCESS = "FORM_SUBMIT_SUCCESS";
export const FORM_SUBMIT_ERROR = "FORM_SUBMIT_ERROR";
export const FORM_RESET = "FORM_RESET";
export const FORM_INIT_UPDATE = "FORM_INIT_UPDATE";
export const UPDATE_HELPER_TEXT_VIEW = "UPDATE_HELPER_TEXT_VIEW";
export const UPDATE_HELPER_FLAG = "UPDATE_HELPER_FLAG";
export const GET_FORM_LOADING = "GET_FORM_LOADING";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_ERROR = "GET_FORM_ERROR";
export const UPDATE_API_META = "UPDATE_API_META";
