export const TOGGLE_LEFT_MENU = "TOGGLE_LEFT_MENU";
export const TOGGLE_LEFT_MENU_ITEM_STATE = "TOGGLE_LEFT_MENU_ITEM_STATE";
export const TOGGLE_RIGHT_MENU = "TOGGLE_RIGHT_MENU";
export const BUILD_MENU_ROLE_PERMISSIONS = "BUILD_MENU_ROLE_PERMISSIONS";
