export const SET_PENDING_REQUESTS = "SET_PENDING_REQUESTS";
export const REMOVE_PENDING_REQUESTS = "REMOVE_PENDING_REQUESTS";

export const TOKEN_REQUESTED = "TOKEN_REQUESTED";
export const TOKEN_REJUVINATED = "TOKEN_REJUVINATED";
