
export const LOCAL_THEMES_SYNCED_SUCCESS = "LOCAL_THEMES_SYNCED_SUCCESS";
export const LOCAL_THEMES_SYNCED_FAILURE = "LOCAL_THEMES_SYNCED_FAILURE";
export const GET_THEMES_SUCCESS = "GET_THEMES_SUCCESS";
export const GET_THEMES_FAILURE = "GET_THEMES_FAILURE";
export const SET_LOCAL_THEMES_SUCCESS = "SET_LOCAL_THEMES_SUCCESS";