import { changePrimaryContact } from "./asyncSelectCustomFunctions";
import {
  checkEmailorPhone,
  complaint,
  confirmPassword,
  consultationTimings,
  createAppointment,
  createDoctor,
  createMailTemplateSchema,
  createPatient,
  createPatientRelative,
  createSMSTemplateSchema,
  createWhatsappTemplateSchema,
  diagnoses,
  enterPassword,
  followup,
  guideline,
  history,
  mailCommunicationTemplateSchema,
  prescriptionClinic,
  prescriptionClinicSearch,
  prescriptionPatientSearch,
  procedure,
  profileBaic,
  profileEducation,
  profileExperience,
  profileRegistration,
  reffer,
  smsCommunicationTemplateSchema,
  stringValueManager,
  testMailCommunicationTemplateSchema,
  testSMSCommunicationTemplateSchema,
  updateMailTemplateSchema,
  updateSMSTemplateSchema,
  updateWhatsappTemplateSchema,
  whatsappCommunicationTemplateSchema
} from "./formikSchema";
import { FORM_IDS } from "../components/forms/coreFormConstants";

export const FORM_VALIDATION_MAP = {
  changePrimaryContact               : changePrimaryContact,
  checkEmailorPhone                  : checkEmailorPhone,
  complaint                          : complaint,
  confirmPassword                    : confirmPassword,
  createDoctor                       : createDoctor,
  createMailTemplateSchema           : createMailTemplateSchema,
  [FORM_IDS.__PROFILE_EXPERIENCE]    : profileExperience,
  [FORM_IDS.__PROFILE_EDUCATION]     : profileEducation,
  createPatient                      : createPatient,
  createPatientRelative              : createPatientRelative,
  createSMSTemplateSchema            : createSMSTemplateSchema,
  createWhatsappTemplateSchema       : createWhatsappTemplateSchema,
  diagnoses                          : diagnoses,
  enterPassword                      : enterPassword,
  followup                           : followup,
  guideline                          : guideline,
  history                            : history,
  mailCommunicationTemplateSchema    : mailCommunicationTemplateSchema,
  prescriptionClinic                 : prescriptionClinic,
  prescriptionClinicSearch           : prescriptionClinicSearch,
  prescriptionPatientSearch          : prescriptionPatientSearch,
  [FORM_IDS.__CONSULTATION_TIMINGS]  : consultationTimings,
  [FORM_IDS.__CREATE_APPOINTMENT]    : createAppointment,
  [FORM_IDS.__STRING_TABLE_MANAGER]  : stringValueManager,
  procedure                          : procedure,
  profileBaic                        : profileBaic,
  profileRegistration                : profileRegistration,
  reffer                             : reffer,
  smsCommunicationTemplateSchema     : smsCommunicationTemplateSchema,
  testMailCommunicationTemplateSchema: testMailCommunicationTemplateSchema,
  testSMSCommunicationTemplateSchema : testSMSCommunicationTemplateSchema,
  updateMailTemplateSchema           : updateMailTemplateSchema,
  updateSMSTemplateSchema            : updateSMSTemplateSchema,
  updateWhatsappTemplateSchema       : updateWhatsappTemplateSchema,
  whatsappCommunicationTemplateSchema: whatsappCommunicationTemplateSchema,
};
