import {
  changePrimaryContact,
  masterData,
  prescriptionAsyncSelects,
  profileBasicgender,
  profileRegistrationSpecilization,
  searchClinic,
  searchPatient,
} from "./asyncSelectCustomFunctions";

export const __CHANGEPRIMARYCONTACT_GET_OPTION_VALUE = "__CHANGEPRIMARYCONTACT_GET_OPTION_VALUE";
export const __CHANGEPRIMARYCONTACT_GET_OPTION_LABEL = "__CHANGEPRIMARYCONTACT_GET_OPTION_LABEL";
export const __CHANGEPRIMARYCONTACT_IS_OPTIONS_EQUAL_TO_VALUE =
  "__CHANGEPRIMARYCONTACT_IS_OPTIONS_EQUAL_TO_VALUE";
export const __PROFILEBASICGENDER_GET_OPTION_VALUE = "__PROFILEBASICGENDER_GET_OPTION_VALUE";
export const __PROFILEBASICGENDER_GET_OPTION_LABEL = "__PROFILEBASICGENDER_GET_OPTION_LABEL";
export const __PROFILEBASICGENDER_IS_OPTIONS_EQUAL_TO_VALUE =
  "__PROFILEBASICGENDER_IS_OPTIONS_EQUAL_TO_VALUE";
export const __PROFILEREGISTRATIONSPECILIZATION_GET_OPTION_VALUE =
  "__PROFILEREGISTRATIONSPECILIZATION_GET_OPTION_VALUE";
export const __PRESCRIPTIONASYNCSELECTS_GET_OPTION_VALUE =
  "__PRESCRIPTIONASYNCSELECTS_GET_OPTION_VALUE";
export const __PRESCRIPTIONASYNCSELECTS_GET_OPTION_LABEL =
  "__PRESCRIPTIONASYNCSELECTS_GET_OPTION_LABEL";
export const __PRESCRIPTIONASYNCSELECTS_IS_OPTIONS_EQUAL_TO_VALUE =
  "__PRESCRIPTIONASYNCSELECTS_IS_OPTIONS_EQUAL_TO_VALUE";
export const __SEARCHPATIENT_ON_CHANGE_DISPATCH = "__SEARCHPATIENT_ON_CHANGE_DISPATCH";
export const __SEARCHPATIENT_GET_OPTION_VALUE = "__SEARCHPATIENT_GET_OPTION_VALUE";
export const __SEARCHPATIENT_GET_OPTION_LABEL = "__SEARCHPATIENT_GET_OPTION_LABEL";
export const __SEARCHPATIENT_IS_OPTIONS_EQUAL_TO_VALUE =
  "__SEARCHPATIENT_IS_OPTIONS_EQUAL_TO_VALUE";
export const __SEARCH_CLINIC_ON_CHANGE_DISPATCH = "__SEARCH_CLINIC_ON_CHANGE_DISPATCH";
export const __SEARCH_CLINIC_GET_OPTION_VALUE = "__SEARCH_CLINIC_GET_OPTION_VALUE";
export const __SEARCH_CLINIC_GET_OPTION_LABEL = "__SEARCH_CLINIC_GET_OPTION_LABEL";
export const __SEARCH_CLINIC_IS_OPTIONS_EQUAL_TO_VALUE =
  "__SEARCH_CLINIC_IS_OPTIONS_EQUAL_TO_VALUE";

export const ASYNC_SELECT_FUNCTION_MAP = {
  __CHANGEPRIMARYCONTACT_GET_OPTION_VALUE: changePrimaryContact.getOptionValue,
  __CHANGEPRIMARYCONTACT_GET_OPTION_LABEL: changePrimaryContact.getOptionLabel,
  __CHANGEPRIMARYCONTACT_IS_OPTIONS_EQUAL_TO_VALUE: changePrimaryContact.isOptionsEqualToValue,

  __PROFILEBASICGENDER_GET_OPTION_VALUE: profileBasicgender.getOptionValue,
  __PROFILEBASICGENDER_GET_OPTION_LABEL: profileBasicgender.getOptionLabel,
  __PROFILEBASICGENDER_IS_OPTIONS_EQUAL_TO_VALUE: profileBasicgender.isOptionEqualToValue,

  __PROFILEREGISTRATIONSPECILIZATION_GET_OPTION_VALUE:
    profileRegistrationSpecilization.getOptionValue,

  __PRESCRIPTIONASYNCSELECTS_GET_OPTION_VALUE: prescriptionAsyncSelects.getOptionValue,
  __PRESCRIPTIONASYNCSELECTS_GET_OPTION_LABEL: prescriptionAsyncSelects.getOptionLabel,
  __PRESCRIPTIONASYNCSELECTS_IS_OPTIONS_EQUAL_TO_VALUE:
    prescriptionAsyncSelects.isOptionEqualToValue,

  __SEARCHPATIENT_ON_CHANGE_DISPATCH: searchPatient.onChangeDispatch,
  __SEARCHPATIENT_GET_OPTION_VALUE: searchPatient.getOptionValue,
  __SEARCHPATIENT_GET_OPTION_LABEL: searchPatient.getOptionLabel,
  __SEARCHPATIENT_IS_OPTIONS_EQUAL_TO_VALUE: searchPatient.isOptionsEqualToValue,

  __SEARCH_CLINIC_ON_CHANGE_DISPATCH: searchClinic.onChangeDispatch,
  __SEARCH_CLINIC_GET_OPTION_VALUE: searchClinic.getOptionValue,
  __SEARCH_CLINIC_GET_OPTION_LABEL: searchClinic.getOptionLabel,
  __SEARCH_CLINIC_IS_OPTIONS_EQUAL_TO_VALUE: searchClinic.isOptionsEqualToValue,

  __MASTERDATA_GET_OPTION_LABEL: masterData.getOptionLabel,
  __MASTERDATA_GET_OPTION_VALUE: masterData.getOptionValue,
  __MASTERDATA_IS_OPTIONS_EQUAL_TO_VALUE: masterData.isOptionsEqualToValue,
};
