import { FORM_IDS } from "../components/forms/coreFormConstants";
import { changePrimaryContact } from "./asyncSelectCustomFunctions";
import {
  checkEmailorPhone,
  complaint,
  confirmPassword,
  consultationTimings,
  createAppointment,
  createDoctor,
  createMailTemplateSchema,
  createPatient,
  createPatientRelative,
  createSMSTemplateSchema,
  createWhatsappTemplateSchema,
  diagnoses,
  enterPassword,
  followup,
  guideline,
  history,
  mailCommunicationTemplateSchema,
  prescriptionClinic,
  prescriptionClinicSearch,
  prescriptionPatientSearch,
  procedure,
  profileBaic,
  profileEducation,
  profileExperience,
  profileRegistration,
  reffer,
  smsCommunicationTemplateSchema,
  stringValueManager,
  testMailCommunicationTemplateSchema,
  testSMSCommunicationTemplateSchema,
  updateMailTemplateSchema,
  updateSMSTemplateSchema,
  updateWhatsappTemplateSchema,
  whatsappCommunicationTemplateSchema,
} from "./formikSchema";

export const FORM_VALIDATION_MAP = {
  checkEmailorPhone: checkEmailorPhone,
  enterPassword: enterPassword,
  confirmPassword: confirmPassword,
  changePrimaryContact: changePrimaryContact,
  profileBaic: profileBaic,
  profileRegistration: profileRegistration,
  [FORM_IDS.__PROFILE_EXPERIENCE]: profileExperience,
  [FORM_IDS.__PROFILE_EDUCATION]: profileEducation,
  complaint: complaint,
  history: history,
  reffer: reffer,
  guideline: guideline,
  followup: followup,
  diagnoses: diagnoses,
  procedure: procedure,
  prescriptionClinic: prescriptionClinic,
  prescriptionPatientSearch: prescriptionPatientSearch,
  prescriptionClinicSearch: prescriptionClinicSearch,
  createPatient: createPatient,
  createPatientRelative: createPatientRelative,
  createDoctor: createDoctor,
  [FORM_IDS.__CONSULTATION_TIMINGS]: consultationTimings,
  [FORM_IDS.__CREATE_APPOINTMENT]: createAppointment,
  [FORM_IDS.__STRING_TABLE_MANAGER]: stringValueManager,
  mailCommunicationTemplateSchema: mailCommunicationTemplateSchema,
  smsCommunicationTemplateSchema: smsCommunicationTemplateSchema,
  whatsappCommunicationTemplateSchema: whatsappCommunicationTemplateSchema,
  createSMSTemplateSchema: createSMSTemplateSchema,
  updateSMSTemplateSchema: updateSMSTemplateSchema,
  createWhatsappTemplateSchema: createWhatsappTemplateSchema,
  updateWhatsappTemplateSchema: updateWhatsappTemplateSchema,
  createMailTemplateSchema: createMailTemplateSchema,
  updateMailTemplateSchema: updateMailTemplateSchema,
  testMailCommunicationTemplateSchema: testMailCommunicationTemplateSchema,
  testSMSCommunicationTemplateSchema: testSMSCommunicationTemplateSchema,
};
